name: currensee
description: "CurrenSee - Currency conversion app with real-time exchange rates."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State + networking for CurrenSee
  flutter_riverpod: 2.5.1     # UI layer: ProviderScope, ConsumerWidget, WidgetRef
  riverpod: 2.5.1             # Core providers: Provider, StateProvider, FutureProvider
  http: ^1.5.0                 # API calls
  intl: ^0.19.0                # Number formatting
  shared_preferences: ^2.5.3   # Local storage

  # Authentication & User Management
  supabase_flutter: ^2.0.0     # Supabase Flutter SDK

  # UI & Design
  flutter_animate: ^4.5.0      # Smooth animations
  flutter_staggered_animations: ^1.1.1  # Staggered animations
  shimmer: ^3.0.0              # Loading shimmer effects
  lottie: ^3.1.2               # Lottie animations

  # Charts & Analytics
  fl_chart: ^0.69.0            # Beautiful charts
  syncfusion_flutter_charts: ^26.2.14  # Advanced charts

  # Notifications
  flutter_local_notifications: ^18.0.1  # Local notifications
  onesignal_flutter: ^5.0.4    # OneSignal for push notifications
  timezone: ^0.9.4             # Timezone support for notifications

  # Storage & Database
  sqflite: ^2.4.0              # Local SQLite database
  hive: ^2.2.3                 # Fast local storage
  hive_flutter: ^1.1.0         # Hive for Flutter

  # Utilities
  url_launcher: ^6.3.1         # Open URLs
  package_info_plus: ^8.0.2    # App info
  connectivity_plus: ^6.0.5    # Network connectivity
  cached_network_image: ^3.4.1 # Cached images
  dio: ^5.7.0                  # Advanced HTTP client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.1.0
  hive_generator: ^2.0.1       # Hive code generation
  build_runner: ^2.4.13        # Code generation runner
  flutter_launcher_icons: ^0.13.1  # Generate app icons

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/CurrenSee2.png"
  web:
    generate: true
    image_path: "assets/images/CurrenSee2.png"
    background_color: "#4CAF50"
    theme_color: "#4CAF50"
  windows:
    generate: true
    image_path: "assets/images/CurrenSee2.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/CurrenSee2.png"
  linux:
    generate: true
    image_path: "assets/images/CurrenSee2.png"
