name: currency_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State + networking for CurrenSee
  flutter_riverpod: 2.5.1     # UI layer: ProviderScope, ConsumerWidget, WidgetRef
  riverpod: 2.5.1             # Core providers: Provider, StateProvider, FutureProvider
  http: ^1.5.0                 # API calls
  intl: ^0.20.2                # Number formatting
  shared_preferences: ^2.5.3   # Local storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
